### ISSUE TITLE
I can't see navigation icon on my fork

### ISSUE THREAD

**Issue by NiranjanTambe** [learnlatex/learnlatex.github.io#131] opened 2021-02-13 05:26 UTC
This issue is related to [this](https://github.com/learnlatex/learnlatex.github.io/issues/72#issuecomment-773008541) comment. On my fork I am not able to see navigation icons. The website can be found at -

https://niranjantambe.github.io/learnlatex.github.io/mr/

Please see the screenshot attached.

![106842599-54f98e00-66ca-11eb-957e-e149576a42cb](https://user-images.githubusercontent.com/54938729/107842539-16f71b00-6dea-11eb-8c6a-095fd453736a.png)

**Comment by davidcarlisle** [comment] 2021-02-13 15:07
These are CSS styled characters from FontAwesome Jonas's css specifies that to be distributed from the site

```
@font-face {
  font-family: 'FontAwesome';
  font-display: fallback;
  font-style: normal;
  font-weight: 900;
  src: url('/assets/fonts/fa-solid-900.woff2') format('woff2');
}
```

But somewhere along the way this seems to be over-ridden and it's using the Marathi font (Nirmala UI on this machine.)

**Comment by NiranjanTambe** [comment] 2021-02-14 05:07
On my machine it is using Shobhika font, but this is weird. Do you think the problem will disappear when the fork is merged?

**Comment by davidcarlisle** [comment] 2021-02-14 10:19
Yes we should fix but easier to do after it is merged, for the other languages @jonasjacek  css is forcing the Noto Sans font locally distributed from the site but as we have it currently that isn't supporting Marathi so for your files different fonts are being used depending on your local installation. Just leave this open and we can sort out in the end make sure that the icon font is forced with high enough css precedence.  leave this issue open and fix after the merge I would say.

**Comment by jonasjacek** [comment] 2021-02-14 11:09
That's interesting. I will look into this. I decided to load all assets locally to reduce the amount of dependencies for visual presentation to zero. We can always serve specific fonts for certain languages, in case I can not find the root cause.

@NiranjanTambe did you specify a specific font in your browser settings to overwrite web fonts? An extension for example?

**Comment by jonasjacek** [comment] 2021-02-14 11:25
@NiranjanTambe I belive I've found the issue. https://niranjantambe.github.io/learnlatex.github.io/assets/fonts/fa-solid-900.woff2 is installed and referenced correctly in https://niranjantambe.github.io/learnlatex.github.io/assets/css/style.css

However, the reference is based on the root domain. You are running your test environment in a subdirectory "/learnlatex.github.io/" on that domain. That breaks the references. So after merging it should be fine.

**Comment by davidcarlisle** [comment] 2021-02-14 12:09
@jonasjacek  ah good catch. I can't actually remember if that scss is passed through the liquid template engine, but I think it is as it has the --- block at the top? in the page templates for similar things we have for example

   `{{ "/" | absolute_url }}` 

so URL get expanded to whatever the root url for the site is,   but obviously that only works if the file is preprocessed via liquid?

Is it worth merging even the current incomplete files now, to allow checking the integration even if (like the Japanese ones) we disable it from the public top level language menu?

**Comment by NiranjanTambe** [comment] 2021-02-14 16:16
> @NiranjanTambe I belive I've found the issue. https://niranjantambe.github.io/learnlatex.github.io/assets/fonts/fa-solid-900.woff2 is installed and referenced correctly in https://niranjantambe.github.io/learnlatex.github.io/assets/css/style.css
However, the reference is based on the root domain. You are running your test environment in a subdirectory "/learnlatex.github.io/" on that domain. That breaks the references. So after merging it should be fine.

Thank you so much! I will now work without worrying much about those icons :)

**Comment by NiranjanTambe** [comment] 2021-02-14 16:19
> Is it worth merging even the current incomplete files now, to allow checking the integration even if (like the Japanese ones) we disable it from the public top level language menu?

Is it like if I translate more files and then we merge the repo the problems will be increased? If not, then I would suggest let's wait for some more time. I will at least provide all the translations and then we can go through all the tests.

**Closed** 2021-02-27 14:00 UTC
